export const uiText = {
    recordEyebrow: '记录总览',
    accountEyebrow: '账号维护',
    cardViewTitle: '卡片视图',
    tableViewTitle: '数据列表',
    cardViewDescription: '分类会以卡片形式展示，并带出对应的关联记录。',
    tableViewDescription: '在这里统一查看、编辑和删除当前模块的数据。',
    categoryCardTitle: '分类卡片',
    categoryCardDescription: '每个分类独立成卡片，对应的设备或耗材会直接展示在当前分类下。',
    keywordPlaceholder: '请输入关键字',
    currentRecords: '当前记录',
    unnamedRecord: '未命名记录',
    emptyDescription: '暂无补充说明。',
    emptyRelatedRecords: '当前卡片下暂无关联记录。',
    emptyCategoryDescription: '暂无分类说明。',
    unnamedCategory: '未命名分类',
    emptyCategoryRecords: '当前分类下暂无记录。',
    defaultCreateText: '新增记录',
    defaultCategoryCreateText: '新增分类',
    createSuccess: '创建成功',
    updateSuccess: '更新成功',
    deleteSuccess: '删除成功',
    relatedSyncFailed: '主数据已刷新，但关联记录同步失败，请稍后重试',
    categoryRelatedSyncFailed: '分类已刷新，但关联记录同步失败，请稍后重试',
} as const
